name: Publish
on: push
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@master
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: Install rendering tool
        run: go install github.com/peterbourgon/grender@v1.1.0
      - name: Render
        run: make
      - name: Show results
        run: tree output
      - name: Deploy
        if: github.ref == 'refs/heads/source'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master
          folder: output
          commit-message: Deploying site
